<?php
return [
    "COUNTRIES" => '[{
    "code": "AL",
    "name": "Albania"
}, {
    "code": "DZ",
    "name": "Algeria"
}, {
    "code": "AO",
    "name": "Angola"
}, {
    "code": "AG",
    "name": "Antigua and Barbuda"
}, {
    "code": "AR",
    "name": "Argentina"
}, {
    "code": "AM",
    "name": "Armenia"
}, {
    "code": "AU",
    "name": "Australia"
}, {
    "code": "AT",
    "name": "Austria"
}, {
    "code": "AZ",
    "name": "Azerbaijan"
}, {
    "code": "BS",
    "name": "Bahamas"
}, {
    "code": "BH",
    "name": "Bahrain"
}, {
    "code": "BD",
    "name": "Bangladesh"
}, {
    "code": "BY",
    "name": "Belarus"
}, {
    "code": "BE",
    "name": "Belgium"
}, {
    "code": "BZ",
    "name": "Belize"
}, {
    "code": "BJ",
    "name": "Benin"
}, {
    "code": "BO",
    "name": "Bolivia"
}, {
    "code": "BA",
    "name": "Bosnia and Herzegovina"
}, {
    "code": "BW",
    "name": "Botswana"
}, {
    "code": "BR",
    "name": "Brazil"
}, {
    "code": "BG",
    "name": "Bulgaria"
}, {
    "code": "BF",
    "name": "Burkina Faso"
}, {
    "code": "KH",
    "name": "Cambodia"
}, {
    "code": "CM",
    "name": "Cameroon"
}, {
    "code": "CA",
    "name": "Canada"
}, {
    "code": "CV",
    "name": "Cape Verde"
}, {
    "code": "CL",
    "name": "Chile"
}, {
    "code": "CN",
    "name": "China"
}, {
    "code": "CO",
    "name": "Colombia"
}, {
    "code": "CR",
    "name": "Costa Rica"
}, {
    "code": "HR",
    "name": "Croatia"
}, {
    "code": "CU",
    "name": "Cuba"
}, {
    "code": "CY",
    "name": "Cyprus"
}, {
    "code": "CZ",
    "name": "Czech Republic"
}, {
    "code": "DK",
    "name": "Denmark"
}, {
    "code": "DO",
    "name": "Dominican Republic"
}, {
    "code": "EC",
    "name": "Ecuador"
}, {
    "code": "EG",
    "name": "Egypt"
}, {
    "code": "SV",
    "name": "El Salvador"
}, {
    "code": "EE",
    "name": "Estonia"
}, {
    "code": "FJ",
    "name": "Fiji"
}, {
    "code": "FI",
    "name": "Finland"
}, {
    "code": "FR",
    "name": "France"
}, {
    "code": "GA",
    "name": "Gabon"
}, {
    "code": "DE",
    "name": "Germany"
}, {
    "code": "GH",
    "name": "Ghana"
}, {
    "code": "GR",
    "name": "Greece"
}, {
    "code": "GT",
    "name": "Guatemala"
}, {
    "code": "GW",
    "name": "Guinea-Bissau"
}, {
    "code": "HT",
    "name": "Haiti"
}, {
    "code": "HN",
    "name": "Honduras"
}, {
    "code": "HK",
    "name": "Hong Kong"
}, {
    "code": "HU",
    "name": "Hungary"
}, {
    "code": "IS",
    "name": "Iceland"
}, {
    "code": "IN",
    "name": "India"
}, {
    "code": "ID",
    "name": "Indonesia"
}, {
    "code": "IR",
    "name": "Iran"
}, {
    "code": "IE",
    "name": "Ireland"
}, {
    "code": "IL",
    "name": "Israel"
}, {
    "code": "IT",
    "name": "Italy"
}, {
    "code": "CI",
    "name": "Ivory Coast"
}, {
    "code": "JM",
    "name": "Jamaica"
}, {
    "code": "JP",
    "name": "Japan"
}, {
    "code": "JO",
    "name": "Jordan"
}, {
    "code": "KZ",
    "name": "Kazakhstan"
}, {
    "code": "KE",
    "name": "Kenya"
}, {
    "code": "KR",
    "name": "Korea"
}, {
    "code": "KW",
    "name": "Kuwait"
}, {
    "code": "KG",
    "name": "Kyrgyzstan"
}, {
    "code": "LA",
    "name": "Laos"
}, {
    "code": "LV",
    "name": "Latvia"
}, {
    "code": "LB",
    "name": "Lebanon"
}, {
    "code": "LI",
    "name": "Liechtenstein"
}, {
    "code": "LT",
    "name": "Lithuania"
}, {
    "code": "LU",
    "name": "Luxembourg"
}, {
    "code": "MO",
    "name": "Macau"
}, {
    "code": "MK",
    "name": "Macedonia"
}, {
    "code": "MY",
    "name": "Malaysia"
}, {
    "code": "ML",
    "name": "Mali"
}, {
    "code": "MT",
    "name": "Malta"
}, {
    "code": "MU",
    "name": "Mauritius"
}, {
    "code": "MX",
    "name": "Mexico"
}, {
    "code": "MD",
    "name": "Moldova"
}, {
    "code": "MA",
    "name": "Morocco"
}, {
    "code": "MZ",
    "name": "Mozambique"
}, {
    "code": "MM",
    "name": "Myanmar"
}, {
    "code": "NA",
    "name": "Namibia"
}, {
    "code": "NP",
    "name": "Nepal"
}, {
    "code": "NL",
    "name": "Netherlands"
}, {
    "code": "AN",
    "name": "Netherlands Antilles"
}, {
    "code": "NZ",
    "name": "New Zealand"
}, {
    "code": "NI",
    "name": "Nicaragua"
}, {
    "code": "NE",
    "name": "Niger"
}, {
    "code": "NG",
    "name": "Nigeria"
}, {
    "code": "NO",
    "name": "Norway"
}, {
    "code": "OM",
    "name": "Oman"
}, {
    "code": "PK",
    "name": "Pakistan"
}, {
    "code": "PA",
    "name": "Panama"
}, {
    "code": "PG",
    "name": "Papua New Guinea"
}, {
    "code": "PY",
    "name": "Paraguay"
}, {
    "code": "PE",
    "name": "Peru"
}, {
    "code": "PH",
    "name": "Philippines"
}, {
    "code": "PL",
    "name": "Poland"
}, {
    "code": "PT",
    "name": "Portugal"
}, {
    "code": "QA",
    "name": "Qatar"
}, {
    "code": "RO",
    "name": "Romania"
}, {
    "code": "RU",
    "name": "Russia"
}, {
    "code": "RW",
    "name": "Rwanda"
}, {
    "code": "SA",
    "name": "Saudi Arabia"
}, {
    "code": "SN",
    "name": "Senegal"
}, {
    "code": "RS",
    "name": "Serbia"
}, {
    "code": "SG",
    "name": "Singapore"
}, {
    "code": "SK",
    "name": "Slovakia"
}, {
    "code": "SI",
    "name": "Slovenia"
}, {
    "code": "ZA",
    "name": "South Africa"
}, {
    "code": "ES",
    "name": "Spain"
}, {
    "code": "LK",
    "name": "Sri Lanka"
}, {
    "code": "SD",
    "name": "Sudan"
}, {
    "code": "SE",
    "name": "Sweden"
}, {
    "code": "CH",
    "name": "Switzerland"
}, {
    "code": "TW",
    "name": "Taiwan"
}, {
    "code": "TJ",
    "name": "Tajikistan"
}, {
    "code": "TZ",
    "name": "Tanzania"
}, {
    "code": "TH",
    "name": "Thailand"
}, {
    "code": "TG",
    "name": "Togo"
}, {
    "code": "TT",
    "name": "Trinidad and Tobago"
}, {
    "code": "TN",
    "name": "Tunisia"
}, {
    "code": "TR",
    "name": "Turkey"
}, {
    "code": "TM",
    "name": "Turkmenistan"
}, {
    "code": "UG",
    "name": "Uganda"
}, {
    "code": "UA",
    "name": "Ukraine"
}, {
    "code": "AE",
    "name": "United Arab Emirates"
}, {
    "code": "GB",
    "name": "United Kingdom"
}, {
    "code": "US",
    "name": "United States"
}, {
    "code": "UY",
    "name": "Uruguay"
}, {
    "code": "UZ",
    "name": "Uzbekistan"
}, {
    "code": "VE",
    "name": "Venezuela"
}, {
    "code": "VN",
    "name": "Vietnam"
}, {
    "code": "YE",
    "name": "Yemen"
}, {
    "code": "ZM",
    "name": "Zambia"
}, {
    "code": "ZW",
    "name": "Zimbabwe"
}, {
    "code": "00",
    "name": "Other Country"
}]'
];